### ISSUE TITLE
This browser or app may not be secure. Learn more  Try using a different browser. If youâ€™re already using a supported browser, you can try again to sign in.

### ISSUE THREAD

**Issue by hoangquocvietbro** [hostkimjang/youtube-auto-uploader#1]
I get this error This browser or app may not be secure. [Learn more](https://support.google.com/accounts/answer/7675428?hl=en-US)

Try using a different browser. If youâ€™re alreThis browser or app may not be secure. [Learn more](https://support.google.com/accounts/answer/7675428?hl=en-US)

Try using a different browser. If youâ€™re already using a supported browser, you can try again to sign in.ady using a supported browser, you can try again to sign in. How to fix

**Comment by hostkimjang** [comment]
Did you install the latest webdriver through chrome driver-autoinstaller?
Did you change or webdriver options?

**Comment by hoangquocvietbro** [comment]
thanks. I run it on google colab . This error was fix
